export const apiKey = '82230d50b1c5444fb0d83023240112';

export const weatherImages = {
    'Partly cloudy': require('../assets/weatherImages/partlyCloudy.png'), 
    'Partly Cloudy ': require('../assets/weatherImages/partlyCloudy.png'), 
    'Partly Cloudy': require('../assets/weatherImages/partlyCloudy.png'), 
    'Moderate rain': require('../assets/weatherImages/moderateRain.png'), 
    'Moderate Rain ': require('../assets/weatherImages/moderateRain.png'), 
    'Patchy rain possible': require('../assets/weatherImages/moderateRain.png'), 
    'Patchy rain possible ': require('../assets/weatherImages/moderateRain.png'), 
    'Patchy rain nearby': require('../assets/weatherImages/moderateRain.png'), 
    'Patchy rain nearby ': require('../assets/weatherImages/moderateRain.png'), 
    'Patchy moderate snow': require('../assets/weatherImages/snow.png'), 
    'Patchy moderate snow ': require('../assets/weatherImages/snow.png'), 
    'Light snow': require('../assets/weatherImages/snow.png'), 
    'Moderate snow': require('../assets/weatherImages/snow.png'), 
    'Heavy snow': require('../assets/weatherImages/snow.png'), 
    'Blowing snow': require('../assets/weatherImages/snow.png'), 
    'Sunny': require('../assets/weatherImages/sun.png'), 
    'Sunny ': require('../assets/weatherImages/sun.png'), 
    'Clear': require('../assets/weatherImages/sun.png'), 
    'Clear ': require('../assets/weatherImages/sun.png'), 
    'Overcast': require('../assets/weatherImages/cloud.png'),
    'Overcast ': require('../assets/weatherImages/cloud.png'),
    'Cloudy': require('../assets/weatherImages/cloud.png'),
    'Cloudy': require('../assets/weatherImages/cloud.png'),
    'Fog ': require('../assets/weatherImages/cloud.png'),
    'Fog': require('../assets/weatherImages/cloud.png'),
    'Light rain': require('../assets/weatherImages/moderateRain.png'),
    'Light Rain ': require('../assets/weatherImages/moderateRain.png'),
    'Moderate rain at times': require('../assets/weatherImages/moderateRain.png'),
    'Moderate rain at times ': require('../assets/weatherImages/moderateRain.png'),
    'Heavy rain': require('../assets/weatherImages/heavyrain.png'),
    'Heavy Rain': require('../assets/weatherImages/heavyrain.png'),
    'Heavy rain at times': require('../assets/weatherImages/heavyrain.png'),
    'Heavy rain at times ': require('../assets/weatherImages/heavyrain.png'),
    'Light freezing rain': require('../assets/weatherImages/heavyrain.png'), 
    'Light freezing rain ': require('../assets/weatherImages/heavyrain.png'), 
    'Moderate or heavy snow showers': require('../assets/weatherImages/snow.png'), 
    'Moderate or heavy freezing rain': require('../assets/weatherImages/heavyrain.png'), 
    'Moderate or heavy freezing rain ': require('../assets/weatherImages/heavyrain.png'), 
    'Moderate or heavy rain shower': require('../assets/weatherImages/heavyrain.png'), 
    'Moderate or heavy rain shower ': require('../assets/weatherImages/heavyrain.png'), 
    'Moderate or heavy rain with thunder': require('../assets/weatherImages/heavyrain.png'),
    'Moderate or heavy rain with thunder ': require('../assets/weatherImages/heavyrain.png'),
    'Light sleet': require('../assets/weatherImages/sleet.png'),
    'Light Sleet': require('../assets/weatherImages/sleet.png'),
    'Light Sleet ': require('../assets/weatherImages/sleet.png'),
    'Moderate sleet': require('../assets/weatherImages/sleet.png'),
    'Moderate Sleet': require('../assets/weatherImages/sleet.png'),
    'Heavy sleet': require('../assets/weatherImages/sleet.png'),
    'Heavy Sleet': require('../assets/weatherImages/sleet.png'),
    'Mist': require('../assets/weatherImages/partlyCloudy.png'),
    'other': require('../assets/weatherImages/moderateRain.png')
}